---
- name: create sandbox user
  user: name={{ sandbox_user }}
        shell=/bin/false
        createhome=no
        state=present

- name: add sudoers config for sandbox user
  template: src=sudoers.j2
            dest=/etc/sudoers.d/50-{{ sandbox_user }}-{{ server_name }}
            mode=0440
            owner=root
            group=root
            validate='visudo -c -f %s'

- name: install iptables-persistent package
  apt: name=iptables-persistent
       state=present

- name: check if iptables configured for sandbox user
  shell: iptables -L | grep -q "drop outgoing packets for sandbox user"
  register: check_sandbox_iptables
  ignore_errors: true
  changed_when: no

- name: set iptables to drop outgoing packets for sandbox user
  shell: iptables -A OUTPUT -m owner --uid-owner $(id -u {{ sandbox_user}})
           -m comment --comment "drop outgoing packets for sandbox user" -j DROP
  when: check_sandbox_iptables | failed
  notify:
    - save iptables

- include: sandbox_apparmor.yml tags=sandbox,apparmor

- name: create sandbox base directory
  file: path={{ sandbox_dir }}
        state=directory
        owner={{ sandbox_user }}
        group={{ sandbox_user }}

- include: sandbox_python.yml
- include: sandbox_java.yml
  sudo_user: "{{ sandbox_user }}"
